2020-08-08 01:38:21,098 - [testcase.py-->line:29] - ERROR: 账号为空:用例执行失败，失败的信息如下
2020-08-08 01:38:21,098 - [testcase.py-->line:30] - ERROR: {'code': 1, 'msg': '所有的参数不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '所有的参数不能为空'}
?                     ^^^^^ ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                     ^^^^^ ^^
Traceback (most recent call last):
  File "D:\PycharmProjects\py31_test_project\testcase\testcase.py", line 26, in test_login_case
    self.assertEqual(expected, actual)
  File "D:\Python3.7\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\Python3.7\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "D:\Python3.7\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'code': 1, 'msg': '所有的参数不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '所有的参数不能为空'}
?                     ^^^^^ ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                     ^^^^^ ^^

2020-08-08 01:38:21,237 - [testcase.py-->line:29] - ERROR: 密码为空:用例执行失败，失败的信息如下
2020-08-08 01:38:21,238 - [testcase.py-->line:30] - ERROR: {'code': 1, 'msg': '所有的参数不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '所有的参数不能为空'}
?                     ^^^^^ ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                     ^^^^^ ^^
Traceback (most recent call last):
  File "D:\PycharmProjects\py31_test_project\testcase\testcase.py", line 26, in test_login_case
    self.assertEqual(expected, actual)
  File "D:\Python3.7\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\Python3.7\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "D:\Python3.7\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'code': 1, 'msg': '所有的参数不能为空'} != {'code': 1, 'msg': '账号或密码不正确'}
- {'code': 1, 'msg': '所有的参数不能为空'}
?                     ^^^^^ ^^^

+ {'code': 1, 'msg': '账号或密码不正确'}
?                     ^^^^^ ^^

2020-08-08 01:38:22,413 - [testcase.py-->line:48] - ERROR: 账号大于18位:用例执行失败，失败的信息如下
2020-08-08 01:38:22,414 - [testcase.py-->line:50] - ERROR: {'code': 0, 'msg': '账号和密码必须在6-18位之间'} != {'code': 1, 'msg': '注册成功'}
- {'code': 0, 'msg': '账号和密码必须在6-18位之间'}
+ {'code': 1, 'msg': '注册成功'}
Traceback (most recent call last):
  File "D:\PycharmProjects\py31_test_project\testcase\testcase.py", line 44, in test_register_case
    self.assertEqual(expected, actual)
  File "D:\Python3.7\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\Python3.7\lib\unittest\case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "D:\Python3.7\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'code': 0, 'msg': '账号和密码必须在6-18位之间'} != {'code': 1, 'msg': '注册成功'}
- {'code': 0, 'msg': '账号和密码必须在6-18位之间'}
+ {'code': 1, 'msg': '注册成功'}
